#server:
#  port: 8080
#  context-path: /girl
#
#cupSize: B
#age: 18
##配置文件里使用配置文件
#content: "cupSize:${cupSize},age:${age}"
#
#girl:
#  cupSize: B
#  age: 18

#更改多环境配置
#Java jar 启动加参数：java -jar target/.jar --spring.profiles.active=dev (or prod)
spring:
  profiles:
    active: dev